import { useState, useEffect, useCallback, useRef } from 'react';
import { supabase } from '../../lib/supabase';
import {
  Plus, Trash2, Search, X, ChevronDown, ChevronUp, Package, RefreshCw, Sparkles,
} from 'lucide-react';
import { BudgetElement, BudgetGlobalParam, BudgetFoundationParam, fmtBRL } from './types';
import { calcElementMaterials, LineItemDraft } from './calcElementMaterials';

interface StoredLineItem {
  id: string;
  budget_id: string;
  wbs_step_id: string | null;
  element_id: string | null;
  material_id: string | null;
  product_id: string | null;
  description: string;
  unit: string;
  quantity: number;
  unit_price: number;
  total_price: number;
  is_auto_calculated: boolean;
  source_param_key: string | null;
  sort_order: number;
  materials?: { name: string; unit: string; unit_cost: number | null };
  products?: { name: string; unit: string; sale_price: number; final_sale_price: number | null };
}

interface CatalogItem {
  id: string;
  name: string;
  unit: string;
  unit_price: number;
  type: 'material' | 'product';
}

interface Props {
  element: BudgetElement;
  budgetId: string;
  globalParams: BudgetGlobalParam[];
  foundationParam: BudgetFoundationParam | null;
  isExpanded: boolean;
  onToggle: () => void;
  onTotalChange: (elementId: string, total: number) => void;
  autoGenerate?: boolean;
}

export default function ElementMaterialSummary({
  element, budgetId, globalParams, foundationParam,
  isExpanded, onToggle, onTotalChange, autoGenerate,
}: Props) {
  const [items, setItems] = useState<StoredLineItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const autoGeneratedRef = useRef(false);
  const [catalog, setCatalog] = useState<CatalogItem[]>([]);
  const [catalogSearch, setCatalogSearch] = useState('');
  const [showCatalogFor, setShowCatalogFor] = useState<string | null>(null);
  const [newRow, setNewRow] = useState<{ description: string; unit: string; quantity: string }>({
    description: '', unit: 'un', quantity: '1',
  });
  const [addingManual, setAddingManual] = useState(false);
  const [manualSearch, setManualSearch] = useState('');
  const searchRef = useRef<HTMLInputElement>(null);

  const total = items.reduce((sum, i) => sum + (i.total_price || 0), 0);

  const loadItems = useCallback(async () => {
    setLoading(true);
    const { data } = await supabase
      .from('budget_element_line_items')
      .select(`*, materials(name,unit,unit_cost), products(name,unit,sale_price,final_sale_price)`)
      .eq('element_id', element.id)
      .order('sort_order');
    setItems(data || []);
    setLoading(false);
  }, [element.id]);

  useEffect(() => { if (isExpanded) loadItems(); }, [isExpanded, loadItems]);

  useEffect(() => {
    onTotalChange(element.id, total);
  }, [total, element.id, onTotalChange]);

  const loadCatalog = useCallback(async () => {
    if (catalog.length > 0) return;
    const [{ data: mats }, { data: prods }] = await Promise.all([
      supabase.from('materials').select('id,name,unit,unit_cost').order('name'),
      supabase.from('products').select('id,name,unit,sale_price,final_sale_price').order('name'),
    ]);
    const matItems: CatalogItem[] = (mats || []).map(m => ({
      id: m.id, name: m.name, unit: m.unit,
      unit_price: m.unit_cost || 0, type: 'material' as const,
    }));
    const prodItems: CatalogItem[] = (prods || []).map(p => ({
      id: p.id, name: p.name, unit: p.unit,
      unit_price: p.final_sale_price || p.sale_price || 0, type: 'product' as const,
    }));
    setCatalog([...matItems, ...prodItems]);
  }, [catalog.length]);

  useEffect(() => {
    if (isExpanded) loadCatalog();
  }, [isExpanded, loadCatalog]);

  const generateAutoItems = async () => {
    setSaving(true);
    const numParams: Record<string, number> = {};
    Object.entries(element.params).forEach(([k, v]) => { numParams[k] = Number(v); });
    const drafts = calcElementMaterials(element.element_type, numParams, globalParams, foundationParam);
    if (drafts.length === 0) {
      setSaving(false);
      return;
    }

    await supabase
      .from('budget_element_line_items')
      .delete()
      .eq('element_id', element.id)
      .eq('is_auto_calculated', true);

    const maxOrder = items.filter(i => !i.is_auto_calculated).length;
    const rows = await Promise.all(
      drafts.map(async (d, idx) => {
        let unit_price = 0;
        if (d.material_id) {
          const { data } = await supabase.from('materials').select('unit_cost').eq('id', d.material_id).maybeSingle();
          unit_price = data?.unit_cost || 0;
        } else if (d.product_id) {
          const { data } = await supabase.from('products').select('sale_price,final_sale_price').eq('id', d.product_id).maybeSingle();
          unit_price = data?.final_sale_price || data?.sale_price || 0;
        }
        return {
          budget_id: budgetId,
          wbs_step_id: element.wbs_step_id,
          element_id: element.id,
          material_id: d.material_id,
          product_id: d.product_id,
          description: d.description,
          unit: d.unit,
          quantity: d.quantity,
          unit_price,
          is_auto_calculated: true,
          source_param_key: d.source_param_key,
          sort_order: maxOrder + idx,
        };
      })
    );

    await supabase.from('budget_element_line_items').insert(rows);
    await loadItems();
    setSaving(false);
  };

  useEffect(() => {
    if (autoGenerate && !autoGeneratedRef.current && isExpanded && !loading && items.length === 0) {
      autoGeneratedRef.current = true;
      generateAutoItems(); // eslint-disable-line react-hooks/exhaustive-deps
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, isExpanded, loading, items.length]);

  const addManualItem = async (catalogItem?: CatalogItem) => {
    if (catalogItem) {
      await supabase.from('budget_element_line_items').insert({
        budget_id: budgetId,
        wbs_step_id: element.wbs_step_id,
        element_id: element.id,
        material_id: catalogItem.type === 'material' ? catalogItem.id : null,
        product_id: catalogItem.type === 'product' ? catalogItem.id : null,
        description: catalogItem.name,
        unit: catalogItem.unit,
        quantity: 1,
        unit_price: catalogItem.unit_price,
        is_auto_calculated: false,
        sort_order: items.length,
      });
      await loadItems();
      setAddingManual(false);
      setManualSearch('');
    }
  };

  const addFreeTextItem = async () => {
    if (!newRow.description.trim()) return;
    await supabase.from('budget_element_line_items').insert({
      budget_id: budgetId,
      wbs_step_id: element.wbs_step_id,
      element_id: element.id,
      material_id: null,
      product_id: null,
      description: newRow.description,
      unit: newRow.unit,
      quantity: parseFloat(newRow.quantity) || 1,
      unit_price: 0,
      is_auto_calculated: false,
      sort_order: items.length,
    });
    await loadItems();
    setNewRow({ description: '', unit: 'un', quantity: '1' });
    setAddingManual(false);
  };

  const updateQuantity = async (itemId: string, qty: number) => {
    await supabase.from('budget_element_line_items').update({ quantity: qty }).eq('id', itemId);
    setItems(prev => prev.map(i => i.id === itemId ? { ...i, quantity: qty, total_price: qty * i.unit_price } : i));
    onTotalChange(element.id, items.reduce((sum, i) => sum + (i.id === itemId ? qty * i.unit_price : i.total_price || 0), 0));
  };

  const linkCatalogItem = async (itemId: string, catalogItem: CatalogItem) => {
    await supabase.from('budget_element_line_items').update({
      material_id: catalogItem.type === 'material' ? catalogItem.id : null,
      product_id: catalogItem.type === 'product' ? catalogItem.id : null,
      description: catalogItem.name,
      unit: catalogItem.unit,
      unit_price: catalogItem.unit_price,
    }).eq('id', itemId);
    setShowCatalogFor(null);
    setCatalogSearch('');
    await loadItems();
  };

  const deleteItem = async (itemId: string) => {
    await supabase.from('budget_element_line_items').delete().eq('id', itemId);
    setItems(prev => prev.filter(i => i.id !== itemId));
  };

  const filteredCatalog = catalog.filter(c =>
    catalogSearch.length < 2 || c.name.toLowerCase().includes(catalogSearch.toLowerCase())
  );

  const filteredManualCatalog = catalog.filter(c =>
    manualSearch.length >= 2 && c.name.toLowerCase().includes(manualSearch.toLowerCase())
  );

  const hasAutoItems = items.some(i => i.is_auto_calculated);

  return (
    <div className="border-t border-gray-100">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between px-4 py-2 bg-gray-50 hover:bg-gray-100 transition-colors text-left"
      >
        <div className="flex items-center gap-2">
          <Package className="w-3.5 h-3.5 text-gray-400" />
          <span className="text-xs font-semibold text-gray-600">Resumo de Materiais</span>
          {items.length > 0 && (
            <span className="text-xs bg-orange-100 text-orange-700 px-1.5 py-0.5 rounded font-medium">
              {items.length} {items.length === 1 ? 'item' : 'itens'}
            </span>
          )}
          {total > 0 && (
            <span className="text-xs font-bold text-orange-600">{fmtBRL(total)}</span>
          )}
        </div>
        {isExpanded
          ? <ChevronUp className="w-3.5 h-3.5 text-gray-400" />
          : <ChevronDown className="w-3.5 h-3.5 text-gray-400" />
        }
      </button>

      {isExpanded && (
        <div className="px-4 pb-4 pt-2 bg-gray-50/50">
          {loading ? (
            <div className="flex items-center justify-center py-4 gap-2 text-gray-400 text-xs">
              <RefreshCw className="w-3.5 h-3.5 animate-spin" /> Carregando...
            </div>
          ) : (
            <>
              <div className="flex items-center justify-between mb-2 gap-2">
                <div className="flex gap-1.5">
                  <button
                    onClick={generateAutoItems}
                    disabled={saving}
                    className="flex items-center gap-1 text-xs px-2.5 py-1.5 bg-blue-500 text-white rounded-lg hover:bg-blue-600 disabled:opacity-50 transition-colors"
                  >
                    {saving
                      ? <RefreshCw className="w-3 h-3 animate-spin" />
                      : <Sparkles className="w-3 h-3" />
                    }
                    {hasAutoItems ? 'Recalcular' : 'Gerar Auto'}
                  </button>
                  <button
                    onClick={() => { setAddingManual(true); setTimeout(() => searchRef.current?.focus(), 50); }}
                    className="flex items-center gap-1 text-xs px-2.5 py-1.5 border border-gray-300 text-gray-600 rounded-lg hover:bg-white transition-colors"
                  >
                    <Plus className="w-3 h-3" /> Adicionar Item
                  </button>
                </div>
              </div>

              {addingManual && (
                <div className="mb-3 p-3 bg-white border border-gray-200 rounded-xl shadow-sm">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-semibold text-gray-700">Adicionar Insumo / Produto</span>
                    <button onClick={() => { setAddingManual(false); setManualSearch(''); }} className="p-0.5 hover:bg-gray-100 rounded">
                      <X className="w-3.5 h-3.5 text-gray-400" />
                    </button>
                  </div>
                  <div className="relative mb-2">
                    <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
                    <input
                      ref={searchRef}
                      type="text"
                      placeholder="Buscar insumo ou produto cadastrado..."
                      value={manualSearch}
                      onChange={e => setManualSearch(e.target.value)}
                      className="w-full pl-8 pr-3 py-1.5 text-xs border border-gray-200 rounded-lg focus:ring-1 focus:ring-orange-400 focus:border-orange-400"
                    />
                  </div>
                  {manualSearch.length >= 2 && filteredManualCatalog.length > 0 && (
                    <div className="max-h-40 overflow-y-auto border border-gray-200 rounded-lg bg-white mb-2">
                      {filteredManualCatalog.slice(0, 20).map(c => (
                        <button key={`${c.type}-${c.id}`}
                          onClick={() => addManualItem(c)}
                          className="w-full flex items-center justify-between px-3 py-1.5 hover:bg-orange-50 transition-colors text-left border-b border-gray-50 last:border-0">
                          <div>
                            <span className="text-xs text-gray-800 font-medium">{c.name}</span>
                            <span className={`ml-1.5 text-[10px] px-1 py-0.5 rounded ${c.type === 'material' ? 'bg-blue-50 text-blue-600' : 'bg-green-50 text-green-600'}`}>
                              {c.type === 'material' ? 'Insumo' : 'Produto'}
                            </span>
                          </div>
                          <div className="text-right flex-shrink-0 ml-2">
                            <span className="text-xs text-gray-500">{c.unit}</span>
                            {c.unit_price > 0 && <span className="block text-xs text-emerald-600 font-medium">{fmtBRL(c.unit_price)}</span>}
                          </div>
                        </button>
                      ))}
                    </div>
                  )}
                  {manualSearch.length >= 2 && filteredManualCatalog.length === 0 && (
                    <p className="text-xs text-gray-400 mb-2">Nenhum item encontrado. Adicione como texto livre abaixo.</p>
                  )}
                  <div className="border-t border-gray-100 pt-2">
                    <p className="text-[10px] text-gray-400 mb-1.5 font-medium">Ou adicionar item livre:</p>
                    <div className="flex gap-1.5">
                      <input type="text" placeholder="Descricao" value={newRow.description}
                        onChange={e => setNewRow(p => ({ ...p, description: e.target.value }))}
                        className="flex-1 px-2 py-1.5 text-xs border border-gray-200 rounded-lg focus:ring-1 focus:ring-orange-400 min-w-0" />
                      <input type="text" placeholder="Und" value={newRow.unit}
                        onChange={e => setNewRow(p => ({ ...p, unit: e.target.value }))}
                        className="w-14 px-2 py-1.5 text-xs border border-gray-200 rounded-lg text-center focus:ring-1 focus:ring-orange-400" />
                      <input type="number" placeholder="Qtd" value={newRow.quantity}
                        onChange={e => setNewRow(p => ({ ...p, quantity: e.target.value }))}
                        className="w-16 px-2 py-1.5 text-xs border border-gray-200 rounded-lg text-center focus:ring-1 focus:ring-orange-400" />
                      <button onClick={addFreeTextItem}
                        className="px-3 py-1.5 bg-orange-500 text-white text-xs rounded-lg hover:bg-orange-600 flex-shrink-0">
                        Add
                      </button>
                    </div>
                  </div>
                </div>
              )}

              {items.length > 0 ? (
                <div className="border border-gray-200 rounded-xl overflow-hidden bg-white">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="bg-gray-100 border-b border-gray-200">
                        <th className="text-left px-3 py-2 text-gray-500 font-semibold w-8">#</th>
                        <th className="text-left px-3 py-2 text-gray-500 font-semibold">Produto / Insumo</th>
                        <th className="text-center px-2 py-2 text-gray-500 font-semibold w-14">Und</th>
                        <th className="text-right px-2 py-2 text-gray-500 font-semibold w-20">Quant.</th>
                        <th className="text-right px-3 py-2 text-gray-500 font-semibold w-24">R$ Unit.</th>
                        <th className="text-right px-3 py-2 text-gray-500 font-semibold w-24">Total</th>
                        <th className="w-8"></th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                      {items.map((item, idx) => {
                        const linked = !!item.material_id || !!item.product_id;
                        const isOpen = showCatalogFor === item.id;
                        return (
                          <>
                            <tr key={item.id} className={`hover:bg-gray-50 transition-colors ${item.is_auto_calculated ? 'bg-blue-50/30' : ''}`}>
                              <td className="px-3 py-2 text-gray-400 text-center font-mono">{idx + 1}</td>
                              <td className="px-3 py-2">
                                <div className="flex items-center gap-1.5 min-w-0">
                                  {item.is_auto_calculated && (
                                    <span className="flex-shrink-0 text-[9px] bg-blue-100 text-blue-600 px-1 py-0.5 rounded font-medium">AUTO</span>
                                  )}
                                  {linked ? (
                                    <span className="text-gray-800 font-medium truncate">{item.description}</span>
                                  ) : (
                                    <button
                                      onClick={() => { setShowCatalogFor(isOpen ? null : item.id); setCatalogSearch(''); }}
                                      className="text-left text-amber-700 underline decoration-dotted hover:text-orange-600 truncate"
                                      title="Vincular ao catalogo"
                                    >
                                      {item.description || '(sem descricao)'}
                                    </button>
                                  )}
                                  {!linked && (
                                    <span className="flex-shrink-0 text-[9px] bg-amber-50 text-amber-600 px-1 py-0.5 rounded border border-amber-200">sem preco</span>
                                  )}
                                </div>
                              </td>
                              <td className="px-2 py-2 text-center text-gray-500">{item.unit}</td>
                              <td className="px-2 py-2 text-right">
                                <input
                                  type="number"
                                  min="0"
                                  step="0.001"
                                  defaultValue={item.quantity}
                                  onBlur={e => updateQuantity(item.id, parseFloat(e.target.value) || 0)}
                                  className="w-full text-right text-gray-800 font-medium bg-transparent border-0 focus:bg-white focus:border focus:border-orange-300 rounded px-1 py-0.5 focus:ring-1 focus:ring-orange-300"
                                />
                              </td>
                              <td className="px-3 py-2 text-right text-gray-700">
                                {item.unit_price > 0
                                  ? fmtBRL(item.unit_price)
                                  : <span className="text-gray-300">—</span>
                                }
                              </td>
                              <td className="px-3 py-2 text-right font-semibold text-gray-900">
                                {item.total_price > 0
                                  ? fmtBRL(item.total_price)
                                  : <span className="text-gray-300">—</span>
                                }
                              </td>
                              <td className="px-2 py-2">
                                <button onClick={() => deleteItem(item.id)}
                                  className="p-1 text-gray-300 hover:text-red-500 hover:bg-red-50 rounded transition-colors">
                                  <Trash2 className="w-3 h-3" />
                                </button>
                              </td>
                            </tr>
                            {isOpen && (
                              <tr key={`catalog-${item.id}`}>
                                <td colSpan={7} className="px-3 pb-2">
                                  <div className="bg-white border border-orange-200 rounded-xl p-3 shadow-sm">
                                    <div className="flex items-center gap-2 mb-2">
                                      <Search className="w-3.5 h-3.5 text-gray-400" />
                                      <input
                                        autoFocus
                                        type="text"
                                        placeholder="Buscar no catalogo..."
                                        value={catalogSearch}
                                        onChange={e => setCatalogSearch(e.target.value)}
                                        className="flex-1 text-xs border-0 focus:ring-0 outline-none"
                                      />
                                      <button onClick={() => setShowCatalogFor(null)}>
                                        <X className="w-3.5 h-3.5 text-gray-400 hover:text-gray-600" />
                                      </button>
                                    </div>
                                    <div className="max-h-36 overflow-y-auto divide-y divide-gray-50">
                                      {filteredCatalog.slice(0, 15).map(c => (
                                        <button key={`link-${c.type}-${c.id}`}
                                          onClick={() => linkCatalogItem(item.id, c)}
                                          className="w-full flex items-center justify-between px-2 py-1.5 hover:bg-orange-50 transition-colors text-left">
                                          <div>
                                            <span className="text-xs text-gray-800">{c.name}</span>
                                            <span className={`ml-1.5 text-[10px] px-1 rounded ${c.type === 'material' ? 'bg-blue-50 text-blue-600' : 'bg-green-50 text-green-600'}`}>
                                              {c.type === 'material' ? 'Insumo' : 'Produto'}
                                            </span>
                                          </div>
                                          <div className="flex items-center gap-2 flex-shrink-0 ml-2">
                                            <span className="text-[10px] text-gray-400">{c.unit}</span>
                                            {c.unit_price > 0 && (
                                              <span className="text-xs text-emerald-600 font-medium">{fmtBRL(c.unit_price)}</span>
                                            )}
                                          </div>
                                        </button>
                                      ))}
                                      {catalogSearch.length >= 2 && filteredCatalog.length === 0 && (
                                        <p className="text-xs text-gray-400 py-2 px-2">Nenhum resultado.</p>
                                      )}
                                    </div>
                                  </div>
                                </td>
                              </tr>
                            )}
                          </>
                        );
                      })}
                    </tbody>
                    <tfoot>
                      <tr className="border-t-2 border-gray-200 bg-gray-50">
                        <td colSpan={5} className="px-3 py-2 text-xs font-bold text-gray-700 text-right uppercase tracking-wide">
                          Total do Elemento
                        </td>
                        <td className="px-3 py-2 text-right font-bold text-orange-600">
                          {fmtBRL(total)}
                        </td>
                        <td></td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              ) : (
                <div className="text-center py-5 border border-dashed border-gray-200 rounded-xl">
                  <Package className="w-6 h-6 text-gray-300 mx-auto mb-1.5" />
                  <p className="text-xs text-gray-400 mb-2">Nenhum material adicionado ainda.</p>
                  <p className="text-[11px] text-gray-400">
                    Clique em <strong>Gerar Auto</strong> para calcular materiais a partir dos parametros do elemento,
                    ou em <strong>Adicionar Item</strong> para inserir manualmente.
                  </p>
                </div>
              )}
            </>
          )}
        </div>
      )}
    </div>
  );
}
