/*
  # Create budget_element_line_items table

  ## Summary
  Adds a line-items table for the construction budget module. Each row represents one
  material/product line inside a WBS step or parametric element, enabling a spreadsheet-style
  budget view (QUANT | UND | COD | PRODUTO | R$ UND | TOTAL) grouped by work stage.

  ## New Tables
  - `budget_element_line_items`
    - `id` – primary key
    - `budget_id` – FK to budgets
    - `wbs_step_id` – FK to budget_wbs_steps (which construction stage this item belongs to)
    - `element_id` – FK to budget_elements (nullable – NULL means the item belongs to the stage
      directly, not to a specific parametric element, e.g. Serviços Preliminares manual items)
    - `material_id` – FK to materials (nullable)
    - `product_id` – FK to products (nullable)
    - `description` – free-text description (used when no material/product is linked)
    - `unit` – unit of measure (m3, kg, sc, un, m2, etc.)
    - `quantity` – numeric quantity
    - `unit_price` – price fetched from material.unit_cost or product.sale_price; read-only from catalogue
    - `total_price` – computed: quantity × unit_price
    - `is_auto_calculated` – true when generated by the parametric engine, false for manual entries
    - `source_param_key` – which global param produced this item (e.g. 'traco_concreto_sapata')
    - `sort_order` – display order within the element/step

  ## Security
  - RLS enabled with public read/write (consistent with other budget tables in this project)
*/

CREATE TABLE IF NOT EXISTS budget_element_line_items (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  budget_id          uuid NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
  wbs_step_id        uuid REFERENCES budget_wbs_steps(id) ON DELETE CASCADE,
  element_id         uuid REFERENCES budget_elements(id) ON DELETE CASCADE,
  material_id        uuid REFERENCES materials(id) ON DELETE SET NULL,
  product_id         uuid REFERENCES products(id) ON DELETE SET NULL,
  description        text NOT NULL DEFAULT '',
  unit               text NOT NULL DEFAULT 'un',
  quantity           numeric NOT NULL DEFAULT 0,
  unit_price         numeric NOT NULL DEFAULT 0,
  total_price        numeric GENERATED ALWAYS AS (quantity * unit_price) STORED,
  is_auto_calculated boolean NOT NULL DEFAULT false,
  source_param_key   text,
  sort_order         integer NOT NULL DEFAULT 0,
  created_at         timestamptz DEFAULT now(),
  updated_at         timestamptz DEFAULT now()
);

ALTER TABLE budget_element_line_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read budget_element_line_items"
  ON budget_element_line_items FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Public insert budget_element_line_items"
  ON budget_element_line_items FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Public update budget_element_line_items"
  ON budget_element_line_items FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Public delete budget_element_line_items"
  ON budget_element_line_items FOR DELETE
  TO public
  USING (true);

CREATE INDEX IF NOT EXISTS idx_beli_budget_id    ON budget_element_line_items(budget_id);
CREATE INDEX IF NOT EXISTS idx_beli_wbs_step_id  ON budget_element_line_items(wbs_step_id);
CREATE INDEX IF NOT EXISTS idx_beli_element_id   ON budget_element_line_items(element_id);
